### ISSUE TITLE
[Bug] Startup Crash Android 15

### ISSUE THREAD

**Issue by pwall2222** [Efimj/KotlinNotePadApp#82]
Graphene OS 15
```
Device: Pixel 6a (google - bluejay) SDK: 35 (15) App: 1.9.0 (82)java.lang.IllegalStateException: Error: Placement happened before lookahead.at V6.a.V(Unknown Source:2)at F0.Q.B0(Unknown Source:122)at F0.Q.m0(Unknown Source:5)at D0.e0.k(Unknown Source:62)at A.o0.invoke(Unknown Source:2166)at D0.F.n(Unknown Source:40)at B.s.n(Unknown Source:2)at D0.H.n(Unknown Source:30)at A.D.invoke(Unknown Source:1035)at e0.u.f(Unknown Source:55)at e0.y.a(Unknown Source:51)at e0.z.d(Unknown Source:139)at F0.t0.a(Unknown Source:2)at F0.Q.p(Unknown Source:102)at F0.Q.z0(Unknown Source:122)at F0.v.l0(Unknown Source:43)at D0.e0.l(Unknown Source:25)at A.o0.invoke(Unknown Source:703)at F0.U.n(Unknown Source:6)at F0.D.o1(Unknown Source:107)at F0.D.l0(Unknown Source:29)at D0.e0.g(Unknown Source:67)at D0.i0.invoke(Unknown Source:43)at F0.U.n(Unknown Source:6)at F0.D.o1(Unknown Source:107)at F0.D.l0(Unknown Source:29)at A8.C.invoke(Unknown Source:1137)at e0.u.f(Unknown Source:113)at e0.y.a(Unknown Source:51)at e0.z.d(Unknown Source:139)at F0.t0.a(Unknown Source:2)at F0.Q.A0(Unknown Source:85)at F0.K.Q(Unknown Source:34)at F0.Z.m(Unknown Source:213)at F0.Z.j(Unknown Source:89)at G0.z.v(Unknown Source:35)at G0.z.dispatchDraw(Unknown Source:14)at android.view.View.draw(View.java:24845)at android.view.View.updateDisplayListIfDirty(View.java:23692)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)at android.view.View.updateDisplayListIfDirty(View.java:23646)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)at android.view.View.updateDisplayListIfDirty(View.java:23646)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)at android.view.View.updateDisplayListIfDirty(View.java:23646)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)at android.view.View.updateDisplayListIfDirty(View.java:23646)at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)at android.view.ViewRootImpl.draw(ViewRootImpl.java:5659)at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5312)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4303)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2917)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10324)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)at android.view.Choreographer.doCallbacks(Choreographer.java:1015)at android.view.Choreographer.doFrame(Choreographer.java:945)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)at android.os.Handler.handleCallback(Handler.java:959)at android.os.Handler.dispatchMessage(Handler.java:100)at android.os.Looper.loopOnce(Looper.java:232)at android.os.Looper.loop(Looper.java:317)at android.app.ActivityThread.main(ActivityThread.java:8744)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)at com.android.internal.os.ExecInit.main(ExecInit.java:50)at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by Efimj** [comment]
An intermittent problem, I hope it can be fixed by updating dependencies

**Comment by pwall2222** [comment]
Intermitent across Android + Shkiper versions? 
Or across app launches/app usage.
Because I get that crash any time I try to open the app.

**Comment by Efimj** [comment]
Yes, on different versions of Android this happens randomly, I haven't found a pattern yet. For example, everything works stably for me, maybe I'm just lucky
